package com.xmu.iginx.assoc.modules.data.service.impl;

import com.xmu.iginx.assoc.common.exception.BizException;
import com.xmu.iginx.assoc.framework.iginx.IginxStorageWrapper;
import com.xmu.iginx.assoc.modules.data.dto.DataImportRequest;
import com.xmu.iginx.assoc.modules.data.util.DataFileStorageService;
import com.xmu.iginx.assoc.modules.data.vo.DataImportResultVO;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockMultipartFile;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 数据导入服务测试。
 */
@ExtendWith(MockitoExtension.class)
class DataImportServiceImplTest {

    @Mock
    private IginxStorageWrapper iginxStorageWrapper;

    @Mock
    private DataFileStorageService fileStorageService;

    @InjectMocks
    private DataImportServiceImpl dataImportService;

    @TempDir
    Path tempDir;

    /**
     * ts 路径导入时必须携带时间列 KEY，且需要透传给 LOAD DATA SQL。
     */
    @Test
    void importData_shouldPassColumnKeyForTsPath() {
        Path storedPath = tempDir.resolve("ts-import.csv");
        when(fileStorageService.createFile("dataimport", ".csv"))
            .thenReturn(new DataFileStorageService.StoredFile("ts-import.csv", storedPath));

        DataImportRequest request = new DataImportRequest();
        request.setTargetPath("ts.demo.power");
        request.setKeyMode(DataImportRequest.KeyMode.COLUMN);
        request.setKeyColumn("timestamp");

        MockMultipartFile file = new MockMultipartFile(
            "file",
            "power.csv",
            "text/csv",
            "timestamp,value\n1,100\n2,120\n".getBytes(StandardCharsets.UTF_8)
        );

        DataImportResultVO result = dataImportService.importData(request, file);

        verify(iginxStorageWrapper).executeLoadDataFromCsv(
            storedPath.toAbsolutePath().toString(),
            "ts.demo.power",
            "timestamp"
        );
        assertEquals(2L, result.getTotal());
        assertEquals(2L, result.getSuccess());
        assertEquals(0L, result.getFailed());
        assertFalse(Files.exists(storedPath));
    }

    /**
     * ts 路径导入若未指定列 KEY，应直接拒绝，避免写入语义错误。
     */
    @Test
    void importData_shouldRejectAutoKeyForTsPath() {
        DataImportRequest request = new DataImportRequest();
        request.setTargetPath("ts.demo.power");
        request.setKeyMode(DataImportRequest.KeyMode.AUTO_GENERATED);

        MockMultipartFile file = new MockMultipartFile(
            "file",
            "power.csv",
            "text/csv",
            "timestamp,value\n1,100\n".getBytes(StandardCharsets.UTF_8)
        );

        BizException ex = assertThrows(BizException.class, () -> dataImportService.importData(request, file));
        assertEquals("ts 路径导入必须指定时间列作为 KEY", ex.getMessage());
        verify(fileStorageService, never()).createFile("dataimport", ".csv");
        verify(iginxStorageWrapper, never()).executeLoadDataFromCsv(anyString(), anyString(), anyString());
    }

    /**
     * rt 路径导入默认自动生成 KEY，不应拼接 SET KEY 子句。
     */
    @Test
    void importData_shouldUseAutoGeneratedKeyForRtPath() {
        Path storedPath = tempDir.resolve("rt-import.csv");
        when(fileStorageService.createFile("dataimport", ".csv"))
            .thenReturn(new DataFileStorageService.StoredFile("rt-import.csv", storedPath));

        DataImportRequest request = new DataImportRequest();
        request.setTargetPath("rt.biz.orders");
        request.setKeyMode(DataImportRequest.KeyMode.AUTO_GENERATED);

        MockMultipartFile file = new MockMultipartFile(
            "file",
            "orders.csv",
            "text/csv",
            "id,amount\n1,50\n".getBytes(StandardCharsets.UTF_8)
        );

        DataImportResultVO result = dataImportService.importData(request, file);

        verify(iginxStorageWrapper).executeLoadDataFromCsv(
            storedPath.toAbsolutePath().toString(),
            "rt.biz.orders",
            null
        );
        assertEquals(1L, result.getTotal());
        assertEquals(1L, result.getSuccess());
        assertEquals(0L, result.getFailed());
        assertFalse(Files.exists(storedPath));
        verify(iginxStorageWrapper, never()).executeLoadDataFromCsv(
            storedPath.toAbsolutePath().toString(),
            "rt.biz.orders",
            "id"
        );
    }
}
