package com.xmu.iginx.assoc.modules.data.service.impl;

import cn.edu.tsinghua.iginx.session.Session;
import cn.edu.tsinghua.iginx.thrift.DataType;
import com.xmu.iginx.assoc.common.exception.BizException;
import com.xmu.iginx.assoc.modules.data.dto.DataColumnsDeleteRequest;
import com.xmu.iginx.assoc.framework.iginx.IginxStorageWrapper;
import com.xmu.iginx.assoc.modules.data.dto.StructuredRowCreateRequest;
import com.xmu.iginx.assoc.modules.data.dto.StructuredRowDeleteRequest;
import com.xmu.iginx.assoc.modules.data.dto.StructuredRowUpdateRequest;
import com.xmu.iginx.assoc.modules.data.util.IginxStructuredQueryHelper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * 数据维护服务测试。
 */
@ExtendWith(MockitoExtension.class)
class DataMaintainServiceImplTest {

    @Mock
    private IginxStorageWrapper iginxStorageWrapper;

    @Mock
    private IginxStructuredQueryHelper structuredQueryHelper;

    @Mock
    private Session session;

    @InjectMocks
    private DataMaintainServiceImpl dataMaintainService;

    /**
     * 将 executeWithSession 的回调转发到 mock Session，
     * 便于验证 Java SDK 方法是否被正确调用。
     */
    @BeforeEach
    void setUp() {
        when(iginxStorageWrapper.executeWithSession(any())).thenAnswer(invocation -> {
            @SuppressWarnings("unchecked")
            IginxStorageWrapper.SessionExecutor<Object> executor =
                (IginxStorageWrapper.SessionExecutor<Object>) invocation.getArgument(0);
            return executor.apply(session);
        });
    }

    /**
     * 新增行应优先走 Java SDK 的 insertRowRecords，
     * 且在未显式给 KEY 时自动生成 KEY。
     */
    @Test
    void createStructuredRow_shouldInsertBySdkWithAutoGeneratedKey() throws Exception {
        StructuredRowCreateRequest request = new StructuredRowCreateRequest();
        request.setPath("rt.public.orders");
        LinkedHashMap<String, Object> data = new LinkedHashMap<>();
        data.put("name", "A100");
        data.put("amount", "12.5");
        request.setData(data);

        Map<String, DataType> columnTypes = new LinkedHashMap<>();
        columnTypes.put("name", DataType.BINARY);
        columnTypes.put("amount", DataType.DOUBLE);
        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(columnTypes);

        dataMaintainService.createStructuredRow(request);

        ArgumentCaptor<List<String>> pathCaptor = ArgumentCaptor.forClass(List.class);
        ArgumentCaptor<long[]> keyCaptor = ArgumentCaptor.forClass(long[].class);
        ArgumentCaptor<Object[]> valueCaptor = ArgumentCaptor.forClass(Object[].class);
        ArgumentCaptor<List<DataType>> typeCaptor = ArgumentCaptor.forClass(List.class);

        verify(session).insertRowRecords(pathCaptor.capture(), keyCaptor.capture(), valueCaptor.capture(), typeCaptor.capture(), any());

        assertEquals(List.of("rt.public.orders.name", "rt.public.orders.amount"), pathCaptor.getValue());
        assertNotNull(keyCaptor.getValue());
        assertEquals(1, keyCaptor.getValue().length);

        Object[] rows = valueCaptor.getValue();
        assertNotNull(rows);
        assertEquals(1, rows.length);
        Object[] row = (Object[]) rows[0];
        assertArrayEquals(new Object[]{"A100".getBytes(StandardCharsets.UTF_8), 12.5D}, row);

        assertEquals(List.of(DataType.BINARY, DataType.DOUBLE), typeCaptor.getValue());
    }

    /**
     * 新增行若显式传入 KEY，应使用传入 KEY 写入。
     */
    @Test
    void createStructuredRow_shouldUseProvidedKey() throws Exception {
        StructuredRowCreateRequest request = new StructuredRowCreateRequest();
        request.setPath("rt.public.orders");
        LinkedHashMap<String, Object> data = new LinkedHashMap<>();
        data.put("_iginx_key", "123");
        data.put("amount", "8.8");
        request.setData(data);

        Map<String, DataType> columnTypes = new LinkedHashMap<>();
        columnTypes.put("amount", DataType.DOUBLE);
        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(columnTypes);

        dataMaintainService.createStructuredRow(request);

        ArgumentCaptor<long[]> keyCaptor = ArgumentCaptor.forClass(long[].class);
        verify(session).insertRowRecords(any(), keyCaptor.capture(), any(), any(), any());
        assertArrayEquals(new long[]{123L}, keyCaptor.getValue());
    }

    /**
     * 更新行在“全字段覆盖”时，应采用删后写策略：
     * 先 deleteDataInColumns，再 insertRowRecords。
     */
    @Test
    void updateStructuredRow_shouldDeleteThenInsertWhenFullColumnsProvided() throws Exception {
        StructuredRowUpdateRequest request = new StructuredRowUpdateRequest();
        request.setPath("rt.public.orders");
        LinkedHashMap<String, Object> data = new LinkedHashMap<>();
        data.put("_iginx_key", 42L);
        data.put("name", "B200");
        data.put("amount", 99.6);
        request.setData(data);

        Map<String, DataType> columnTypes = new LinkedHashMap<>();
        columnTypes.put("name", DataType.BINARY);
        columnTypes.put("amount", DataType.DOUBLE);
        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(columnTypes);

        dataMaintainService.updateStructuredRow(request);

        verify(session).deleteDataInColumns(List.of("rt.public.orders.name", "rt.public.orders.amount"), 42L, 43L);
        verify(session).insertRowRecords(any(), any(), any(), any(), any());
    }

    /**
     * 更新行在“部分字段更新”时，应走重写模式，不做整行删除。
     */
    @Test
    void updateStructuredRow_shouldRewriteOnlyWhenPartialColumnsProvided() throws Exception {
        StructuredRowUpdateRequest request = new StructuredRowUpdateRequest();
        request.setPath("rt.public.orders");
        LinkedHashMap<String, Object> data = new LinkedHashMap<>();
        data.put("_iginx_key", 7L);
        data.put("amount", "10.2");
        request.setData(data);

        Map<String, DataType> columnTypes = new LinkedHashMap<>();
        columnTypes.put("name", DataType.BINARY);
        columnTypes.put("amount", DataType.DOUBLE);
        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(columnTypes);

        dataMaintainService.updateStructuredRow(request);

        verify(session, never()).deleteDataInColumns(any(), anyLong(), anyLong());
        ArgumentCaptor<List<String>> pathCaptor = ArgumentCaptor.forClass(List.class);
        ArgumentCaptor<long[]> keyCaptor = ArgumentCaptor.forClass(long[].class);
        ArgumentCaptor<Object[]> valueCaptor = ArgumentCaptor.forClass(Object[].class);
        ArgumentCaptor<List<DataType>> typeCaptor = ArgumentCaptor.forClass(List.class);
        verify(session).insertRowRecords(pathCaptor.capture(), keyCaptor.capture(), valueCaptor.capture(), typeCaptor.capture(), any());

        assertEquals(List.of("rt.public.orders.amount"), pathCaptor.getValue());
        assertArrayEquals(new long[]{7L}, keyCaptor.getValue());
        Object[] rows = valueCaptor.getValue();
        assertNotNull(rows);
        assertEquals(1, rows.length);
        assertArrayEquals(new Object[]{10.2D}, (Object[]) rows[0]);
        assertEquals(List.of(DataType.DOUBLE), typeCaptor.getValue());
    }

    /**
     * 删除行应优先调用 Java SDK 的 deleteDataInColumns。
     */
    @Test
    void deleteStructuredRow_shouldUseSdkDeleteDataInColumns() throws Exception {
        StructuredRowDeleteRequest request = new StructuredRowDeleteRequest();
        request.setPath("rt.public.orders");
        request.setKeys(Map.of("_iginx_key", 1L));

        Map<String, DataType> columnTypes = new LinkedHashMap<>();
        columnTypes.put("name", DataType.BINARY);
        columnTypes.put("amount", DataType.DOUBLE);
        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(columnTypes);

        dataMaintainService.deleteStructuredRow(request);

        verify(session).deleteDataInColumns(List.of("rt.public.orders.name", "rt.public.orders.amount"), 1L, 2L);
        verify(iginxStorageWrapper, never()).executeSql(anyString());
    }

    /**
     * 删除行在无法加载列元数据时，应回退 SQL 删除，保证功能可用。
     */
    @Test
    void deleteStructuredRow_shouldFallbackSqlWhenColumnTypesMissing() {
        StructuredRowDeleteRequest request = new StructuredRowDeleteRequest();
        request.setPath("rt.public.orders");
        request.setKeys(Map.of("_iginx_key", 9L));

        when(structuredQueryHelper.loadColumnTypesByTablePath("rt.public.orders")).thenReturn(Map.of());

        dataMaintainService.deleteStructuredRow(request);

        verify(iginxStorageWrapper).executeSql("DELETE FROM rt.public.orders.* WHERE KEY >= 9 AND KEY <= 9;");
    }

    /**
     * 任务默认输出 task.result.* 也应允许通过 DELETE COLUMNS 清理。
     */
    @Test
    void deleteColumns_shouldAllowTaskResultPrefix() {
        DataColumnsDeleteRequest request = new DataColumnsDeleteRequest();
        request.setPath("task.result.demoTask");
        request.setIncludeChildren(true);

        dataMaintainService.deleteColumns(request);

        verify(iginxStorageWrapper).executeSql("DELETE COLUMNS task.result.demoTask.*;");
    }

    /**
     * 更新请求缺少 KEY 时应立即拒绝。
     */
    @Test
    void updateStructuredRow_shouldRejectWhenKeyMissing() {
        StructuredRowUpdateRequest request = new StructuredRowUpdateRequest();
        request.setPath("rt.public.orders");
        request.setData(Map.of("amount", 1));

        BizException ex = assertThrows(BizException.class, () -> dataMaintainService.updateStructuredRow(request));
        assertEquals("更新请求缺少 KEY/_iginx_key", ex.getMessage());
    }
}
